server:
  port: 8081

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?useSSL=false&serverTimezone=UTC
    username: root
    initialization-mode: always
    platform: oauth